"""Selectors for the alarms table (/alarms). VIRTUALIZED table. Strings ONLY."""
SCROLL = ".custom-scrollbar"
ROWS = ".custom-scrollbar tbody tr"
CELL_NAME = ".cell-name"
CELL_SUBTEXT = ".cell-subtext"
SIGNAL_LINE = ".signal-line"
